import Head from 'next/head';
import PropTypes from 'prop-types';
import Footer from '../../components/Footer/Footer';
import ModalSingIn from '../../components/ModalSingIn/ModalSingIn';
import CardGallery from '../../components/CardGallery/CardGallery';
import styles from '../../styles/Galleries.module.css';
import data from '../../data/galleries.example.json';

const Galleries = ({ gallery }) => {
  return (
    <div className={styles.bgHome}>
      <Head>
        <title>My Queens Club - Enjoy The Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <ModalSingIn idModal='singIn' />
        <h5 className={`text-uppercase fw-bolder text-center py-5 ${styles.title}`}>Galerias</h5>
      </header>

      <main className='mb-5 container-fluid'>
        <section className='row gx-0'>
          {
            gallery.map((info, index) => (
              <div key={index} className='col-6 col-md-4 col-lg-3'>
                <CardGallery {...info} gallery />
              </div>
            ))
          }
        </section>
      </main>

      <Footer />
    </div>
  );
};

export const getStaticPaths = async () => {
  const paths = data.map(queen => {
    return {
      params: { id: queen.idqueen },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (context) => {
  const { id } = context.params;
  const info = data.filter(queen => queen.idqueen === id);

  return {
    props: { gallery: info },
  };
};

Galleries.propTypes = {
  gallery: PropTypes.array,
};

export default Galleries;
