import Head from 'next/head';
import PropTypes from 'prop-types';
import Router, { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Footer from '../../components/Footer/Footer';
import ModalSingIn from '../../components/ModalSingIn/ModalSingIn';
import CardGallery from '../../components/CardGallery/CardGallery';
import styles from '../../styles/Galleries.module.css';
import clientAxios from '../../config/clientAxios';

const Galleries = () => {
  const route = useRouter();
  console.log(route.query.name);
  const [data, setData] = useState();
  useEffect(() => {
    clientAxios(`/galleries/queen/${route.query.name}`)
      .then(res => setData(res.data));
  }, []);

  return (
    <div className={styles.bgHome}>
      <Head>
        <title>My Queens Club - Enjoy The Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <header>
        <ModalSingIn idModal='singIn' />
        <h5 className={`text-uppercase fw-bolder text-center py-5 ${styles.title}`}>Galerias</h5>
      </header>

      <main className='mb-5 container-fluid'>
        <section className='row gx-0'>
          {
            data?.length === 0
              ? <h2 className='text-center text-white'>
                <span style={{ color: '#D44F80', textTransform: 'capitalize' }}>
                  {Router.query.name}</span> NO TIENE GALERIAS DISPONIBLES
              </h2> : data?.map((info, index) => (
                <>
                  <div key={index} className='col-6 col-md-4 col-lg-3'>
                    <CardGallery galeria={info} gallery />
                  </div>

                </>
              ))
          }
        </section>
      </main>

      <Footer />
    </div>
  );
};

/* export const getStaticPaths = async () => {
  const paths = data.map(queen => {
    return {
      params: { id: },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (context) => {
  const userName=localStorage.getItem('user_name')
  const { queen } = context.params;
  const info = await axios(`https://backqueens-production.up.railway.app/purchase/queen/${queen}`)
  const data= await info.data;

  const res=await axios(`https://backqueens-production.up.railway.app/purchase/user/${userName}/${data.gallery}`)
  const gallery=await res.data

  return {
    props: { gallery:gallery },
  };
};
 */
Galleries.propTypes = {

  gallery: PropTypes.array,

};

export default Galleries;
