import Head from 'next/head';
import Footer from '../components/Footer/Footer';
import ModalSingIn from '../components/ModalSingIn/ModalSingIn';

import styles from '../styles/About.module.css';

const About = () => {
  return (
    <div className={styles.bgHome}>
      <Head>
        <title>My Queens Club - Enjoy The Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <ModalSingIn idModal='singIn' />
        <h5 className={`text-uppercase fw-bolder text-center py-5 ${styles.title}`}>Sobre Nosotros</h5>
      </header>

      <main className='mb-5 container-fluid'>
        <section>
          <p className={`m-4 px-3 ${styles.about}`}>Respeto, Compromiso y Sensualidad.</p>
          <p className={`m-4 px-3 ${styles.about}`}>Es un lugar en donde las mujeres pueden expresarse sin ningún tipo de censura,
          y mostrarse como ellas lo deseen a través de fotografías y videos.</p>
          <p className={`m-4 px-3 ${styles.about}`}>En My Queens Club creemos que las mujeres pueden aprovechar su encanto
          físico y obtener beneficios económicos a cambio, estamos convencidos que
          tanto el trabajo de una modelo mostrando su cuerpo desnudo como el de un
          fotógrafo capacitado tiene un valor único, acá no creemos, ni nos importan
          los tabúes que significan la venta de contenido, no tenemos intenciones de
          ser ni vulgares ni sencillos en cuanto al material que ofrecemos, siempre
          optaremos por mostrar el lado más sensual y erótico de cada Queen.</p>
          <p className={`m-4 px-3 ${styles.about}`}>Es primordial para nosotros que cada una de nuestras Queens se sienta cómoda,
          respetada y conforme con el trabajo que realizamos, ellas son las protagonistas
          principales, por eso nos sentimos obligados a que cada una que pase por
          esta experiencia se lleve; no solo un recuerdo de su propia belleza, sino también
          las ganas de volver a My Queens Club.</p>
          <p className={`m-4 px-3 ${styles.about}`}>No nos interesa que seas modelo profesional o no. No te pierdas la oportunidad de
          ser una Queen y quedar en el recuerdo a través de la inmortalización que
          representa una fotografía.</p>
          <p className={`m-4 px-3 ${styles.about}`}>My Queens Club.</p>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default About;
