import Head from 'next/head';
import Carousel from '../components/Carousel/Carousel';
import Footer from '../components/Footer/Footer';
import Tab from '../components/Tab/Tab';
import carouselInfo from '../components/Carousel/carouselData.example.json';
import carouselInfoMobile from '../components/Carousel/carouselDataMobile.example.json';

import styles from '../styles/Home.module.css';
import InfoSection from '../components/InfoSection/InfoSection';
import ModalSingIn from '../components/ModalSingIn/ModalSingIn';
import InfoSubs from '../components/InfoSubs/InfoSubs';
import Checkout from '../components/MercadoPagoPayment/Checkout';

const Home = () => {
  return (
    <div className={styles.bgHome}>
      <Head>
        <title>My Queens Club - Enjoy The Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <ModalSingIn idModal='singIn'/>
        <Carousel carouselInfo={carouselInfo} carouselInfoMobile={carouselInfoMobile} />
      </header>

      <main className='mb-5'>
        <InfoSubs className='my-5' />
        <Tab />
        <InfoSection className="my-5" />
      </main>

      <Footer />
    </div>
  );
};

export async function getStaticProps() {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos/1');
  const data = await res.json();

  return {
    props: { data },
  };
}

export default Home;
